baseURL = "https://tsunamiunleashed.com/"
title = "Tsunami Unleashed"
theme = "relearn"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableGitInfo = true
enableRobotsTXT = true
enableEmoji = true
hasCJKLanguage = false

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 2
endLevel = 4
ordered = false
